Repository opensearch-project/opensearch-java, pull requests merged in 2023-09, with the labels that each got.

#610 Reorganizing user guide and adding working samples
  .gitignore
  USER_GUIDE.md
  guides/auth.md
  guides/bulk.md
  guides/cat.md
  guides/data_stream.md
  guides/point_in_time.md
  guides/search.md
  samples/src/main/java/org/opensearch/client/samples/Bulk.java
  samples/src/main/java/org/opensearch/client/samples/DataStreamBasics.java
  samples/src/main/java/org/opensearch/client/samples/IndexingBasics.java
  samples/src/main/java/org/opensearch/client/samples/PointInTime.java
  samples/src/main/java/org/opensearch/client/samples/Search.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnBasics.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnBooleanFilter.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnPainlessScript.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnScriptScore.java
  samples/src/main/java/org/opensearch/client/samples/util/AppData.java
  samples/src/main/java/org/opensearch/client/samples/util/IndexData.java
  samples/src/main/java/org/opensearch/client/samples/util/RandUtil.java
Labels: skip-changelog

#616 JarHell caused by latest software.amazon.awssdk 2.20.141
  CHANGELOG.md
  java-client/build.gradle.kts
  java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractCatClientIT.java
Labels: bug

#626 [Backport 2.x] Backporting samples and user guide to 2.x
  .gitignore
  USER_GUIDE.md
  guides/auth.md
  guides/bulk.md
  guides/cat.md
  guides/data_stream.md
  guides/plugins/knn.md
  guides/point_in_time.md
  guides/search.md
  samples/build.gradle.kts
  samples/src/main/java/org/opensearch/client/samples/Bulk.java
  samples/src/main/java/org/opensearch/client/samples/DataStreamBasics.java
  samples/src/main/java/org/opensearch/client/samples/IndexingBasics.java
  samples/src/main/java/org/opensearch/client/samples/Main.java
  samples/src/main/java/org/opensearch/client/samples/PointInTime.java
  samples/src/main/java/org/opensearch/client/samples/SampleClient.java
  samples/src/main/java/org/opensearch/client/samples/Search.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnBasics.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnBooleanFilter.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnEfficientFilter.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnPainlessScript.java
  samples/src/main/java/org/opensearch/client/samples/knn/KnnScriptScore.java
  samples/src/main/java/org/opensearch/client/samples/util/AppData.java
  samples/src/main/java/org/opensearch/client/samples/util/IndexData.java
  samples/src/main/java/org/opensearch/client/samples/util/RandUtil.java
  samples/src/main/resources/log4j2.xml
  settings.gradle.kts
Labels: skip-changelog

#627 Added size attribute to MultiTermsAggregation
  CHANGELOG.md
  java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/MultiTermsAggregation.java
  java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractAggregationRequestIT.java
Labels: backport 2.x

#635 Add newer versions of server to compatibility matrix
  .github/workflows/test-integration.yml
  COMPATIBILITY.md
  java-client/src/test/java/org/opensearch/client/opensearch/integTest/OpenSearchJavaClientTestCase.java
Labels: skip-changelog
