Repository opensearch-project/opensearch-java, pull requests merged in 2024-06, with the labels that each got.

#1023 Bump commons-codec:commons-codec from 1.11.0 to 1.17.0 in java-codegen
  java-codegen/build.gradle.kts
Labels: skip-changelog

#1026 Regenerate request/response for the `info` operation
  buildSrc/formatterConfig-generated.xml
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/OpenSearchVersionInfo.java
  java-client/src/generated/java/org/opensearch/client/opensearch/core/InfoRequest.java
  java-client/src/generated/java/org/opensearch/client/opensearch/core/InfoResponse.java
  java-codegen/build.gradle.kts
  java-codegen/opensearch-openapi.yaml
  java-codegen/src/main/java/org/opensearch/client/codegen/Main.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/RequestShape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/SpecTransformer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/openapi/HttpStatusCode.java
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/Builder.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/FieldDoc/Basic.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/FieldDoc/BasicInner.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/FieldDoc/ListAdd.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/FieldDoc/ListAddAll.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/FieldDoc/ListAddBuilderFn.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/RequestShape.mustache
Labels: skip-changelog

#1029 Add `@Generated` annotation to generated classes
  java-client/build.gradle.kts
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/OpenSearchVersionInfo.java
  java-client/src/generated/java/org/opensearch/client/opensearch/core/InfoRequest.java
  java-client/src/generated/java/org/opensearch/client/opensearch/core/InfoResponse.java
  java-codegen/build.gradle.kts
  java-codegen/src/main/java/org/opensearch/client/codegen/CodeGenerator.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/ArrayShape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/EnumShape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Namespace.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/ObjectShape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/RequestShape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Shape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/SpecTransformer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/TaggedUnionShape.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Types.java
  java-codegen/src/main/java/org/opensearch/client/codegen/utils/JavaClassKind.java
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ArrayShape.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/Client.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/EnumShape.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/ObjectShape/ClassDeclaration.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/Partials/ClassDeclaration.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/RequestShape.mustache
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/TaggedUnionShape.mustache
Labels: skip-changelog

#1033 Default analyzer deserialization to custom type when unspecified
  CHANGELOG.md
  java-client/src/main/java/org/opensearch/client/opensearch/_types/analysis/Analyzer.java
  java-client/src/test/java/org/opensearch/client/opensearch/_types/analysis/AnalyzerDeserializerTest.java
Labels: backport 2.x

#1041 Updated CHANGELOG, 2.11.0.
  CHANGELOG.md
Labels: backport 2.x

#1044 Made InlineGet source field nullable
  CHANGELOG.md
  java-client/src/main/java/org/opensearch/client/opensearch/_types/InlineGet.java
  java-client/src/test/java/org/opensearch/client/opensearch/_types/InlineGetTest.java
Labels: backport 2.x

#1039 Document version auto-increment and fix typos.
  RELEASING.md
Labels: backport 2.x, skip-changelog

#1054 Adding @Xtansia to maintainers.
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog
