Repository opensearch-project/opensearch-java, pull requests merged in 2024-09, with the labels that each got.

#1178 Ensure 2.x code gen is correct
  .github/workflows/code-generation.yml
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/ErrorCause.java
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/Result.java
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/ShardFailure.java
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/ShardStatistics.java
  java-client/src/generated/java/org/opensearch/client/opensearch/_types/WriteResponseBase.java
  java-client/src/test/java/org/opensearch/client/opensearch/json/PlainJsonSerializableTest.java
  java-client/src/test/java/org/opensearch/client/opensearch/model/BehaviorsTest.java
  java-codegen/build.gradle.kts
  java-codegen/src/main/java/org/opensearch/client/codegen/CodeGenerator.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/ShapeRenderingContext.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/SpecTransformer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Type.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/TypeParameterDefinition.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/TypeParameterDiamond.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Types.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/overrides/Overrides.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/overrides/PropertyOverride.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/overrides/SchemaOverride.java
  java-codegen/src/main/java/org/opensearch/client/codegen/openapi/OpenApiSchema.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/JavaCodeFormatter.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateGlobalContext.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateLoader.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateRenderer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateValueFormatter.java
  java-codegen/src/main/java/org/opensearch/client/codegen/utils/MapBuilderBase.java
  java-codegen/src/main/java/org/opensearch/client/codegen/utils/ObjectBuilderBase.java
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/Type/directSerializer.mustache
Labels: skip-changelog

#1148 support for withJson-618
  CHANGELOG.md
  guides/json.md
  java-client/src/main/java/org/opensearch/client/json/PlainDeserializable.java
  java-client/src/main/java/org/opensearch/client/opensearch/_types/mapping/SourceField.java
  java-client/src/main/java/org/opensearch/client/opensearch/_types/mapping/TypeMapping.java
  java-client/src/main/java/org/opensearch/client/opensearch/indices/IndexSettings.java
  java-client/src/main/java/org/opensearch/client/opensearch/indices/put_index_template/IndexTemplateMapping.java
  java-client/src/test/java/org/opensearch/client/opensearch/json/PlainDeserializableTest.java
  java-client/src/test/java/org/opensearch/client/opensearch/json/PlainJsonSerializableTest.java
  samples/src/main/java/org/opensearch/client/samples/json/DeserializationBasics.java
Labels: backport 2.x

#1180 Forbid wildcard imports
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/opensearch-java.spotless-conventions.gradle.kts
  java-client/build.gradle.kts
  java-client/src/main/java/org/opensearch/client/opensearch/_types/mapping/IcuCollationKeywordProperty.java
  java-client/src/test/java/org/opensearch/client/opensearch/integTest/aws/AwsSdk2GetRequestIT.java
  java-codegen/build.gradle.kts
  java-codegen/src/main/java/org/opensearch/client/codegen/CodeGenerator.java
  samples/build.gradle.kts
  samples/src/main/java/org/opensearch/client/samples/FlatObjectBasics.java
  samples/src/main/java/org/opensearch/client/samples/IndexTemplates.java
  samples/src/main/java/org/opensearch/client/samples/util/IssueDocument.java
Labels: backport 2.x, skip-changelog

#1183 [Backport 2.x] Forbid wildcard imports (#1180)
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/opensearch-java.spotless-conventions.gradle.kts
  java-client/build.gradle.kts
  java-client/src/main/java/org/opensearch/client/opensearch/_types/mapping/IcuCollationKeywordProperty.java
  java-client/src/test/java/org/opensearch/client/opensearch/integTest/aws/AwsSdk2GetRequestIT.java
  java-codegen/build.gradle.kts
  java-codegen/src/main/java/org/opensearch/client/codegen/CodeGenerator.java
  samples/build.gradle.kts
  samples/src/main/java/org/opensearch/client/samples/FlatObjectBasics.java
  samples/src/main/java/org/opensearch/client/samples/IndexTemplates.java
  samples/src/main/java/org/opensearch/client/samples/util/IssueDocument.java
Labels: skip-changelog

#1185 [Backport main] Add support for codegen overrides
  java-codegen/src/main/java/org/opensearch/client/codegen/CodeGenerator.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/ShapeRenderingContext.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/SpecTransformer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Type.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/TypeParameterDefinition.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/TypeParameterDiamond.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Types.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/overrides/Overrides.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/overrides/PropertyOverride.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/overrides/SchemaOverride.java
  java-codegen/src/main/java/org/opensearch/client/codegen/openapi/OpenApiSchema.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/JavaCodeFormatter.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateGlobalContext.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateLoader.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateRenderer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/renderer/TemplateValueFormatter.java
  java-codegen/src/main/java/org/opensearch/client/codegen/utils/MapBuilderBase.java
  java-codegen/src/main/java/org/opensearch/client/codegen/utils/ObjectBuilderBase.java
  java-codegen/src/main/resources/org/opensearch/client/codegen/templates/Type/directSerializer.mustache
Labels: skip-changelog

#1195 Update Gradle to 8.10.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, skip-changelog

#1198 Support new mechanism of defining deprecated enum variants in OpenAPI
  java-codegen/opensearch-openapi.yaml
  java-codegen/src/main/java/org/opensearch/client/codegen/model/SpecTransformer.java
  java-codegen/src/main/java/org/opensearch/client/codegen/openapi/HttpStatusCode.java
  java-codegen/src/main/java/org/opensearch/client/codegen/openapi/OpenApiSchema.java
  java-codegen/src/main/java/org/opensearch/client/codegen/openapi/OpenApiSchemaFormat.java
Labels: skip-changelog

#1207 Begin generating snapshot namespace
  UPGRADING.md
  java-client/src/generated/java/org/opensearch/client/opensearch/OpenSearchAsyncClientBase.java
  java-client/src/generated/java/org/opensearch/client/opensearch/OpenSearchClientBase.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/CleanupRepositoryRequest.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/CleanupRepositoryResponse.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/CloneSnapshotRequest.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/CloneSnapshotResponse.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/OpenSearchSnapshotAsyncClientBase.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/OpenSearchSnapshotClientBase.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/VerifyRepositoryRequest.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/VerifyRepositoryResponse.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/cleanup_repository/CleanupRepositoryResults.java
  java-client/src/generated/java/org/opensearch/client/opensearch/snapshot/verify_repository/CompactNodeInfo.java
  java-client/src/main/java/org/opensearch/client/opensearch/snapshot/OpenSearchSnapshotAsyncClient.java
  java-client/src/main/java/org/opensearch/client/opensearch/snapshot/OpenSearchSnapshotClient.java
  java-codegen/opensearch-openapi.yaml
  java-codegen/src/main/java/org/opensearch/client/codegen/CodeGenerator.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/Namespace.java
  java-codegen/src/main/java/org/opensearch/client/codegen/model/RequestShape.java
Labels: skip-changelog
