Repository opensearch-project/opensearch-java, pull requests merged in 2024-04, with the labels that each got.

#909 Bumps jackson from 2.15.2 to 2.17.0
  CHANGELOG.md
  java-client/build.gradle.kts
Labels: dependencies

#912 Update to Gradle 8.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#920 Client with Java 8 runtime and Apache HttpClient 5 Transport fails with java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer
  CHANGELOG.md
  java-client/src/main/java/org/opensearch/client/transport/httpclient5/internal/HttpEntityAsyncEntityProducer.java
Labels: bug

#963 Added OpenSearch 2.12 and 2.13 to integration tests.
  .github/workflows/test-integration.yml
Labels: backport 2.x, skip-changelog

#962 [Backport 2.x] Lock MacOS version to 13. (#961)
  .github/workflows/build.yml
  .github/workflows/test-unit.yml
Labels: skip-changelog
