Repository opensearch-project/opensearch-java, pull requests merged in 2024-05, with the labels that each got.

#968 Fix integrationTest builds for JDK-11 sourcesets
  .ci/opensearch/Dockerfile
  .github/workflows/test-integration.yml
  java-client/build.gradle.kts
  java-client/src/test/java11/org/opensearch/client/opensearch/integTest/AbstractSearchRequestIT.java
Labels: skip-changelog

#972 Fix: test.
  java-client/src/test/java11/org/opensearch/client/opensearch/integTest/AbstractSearchRequestIT.java
Labels: backport 2.x, skip-changelog

#1003 ApacheHttpClient5Transport requires Apache Commons Logging dependency
  CHANGELOG.md
  java-client/build.gradle.kts
Labels: bug, backport 2.x

#999 Modify to not use URLEncodedUtils
  CHANGELOG.md
  java-client/src/main/java/org/opensearch/client/transport/endpoints/SimpleEndpoint.java
  java-client/src/main/java/org/opensearch/client/util/PathEncoder.java
  java-client/src/test/java/org/opensearch/client/opensearch/model/EndpointTest.java
  java-client/src/test/java/org/opensearch/client/util/PathEncoderTest.java
Labels: backport 2.x
